[build]
  # Указываем, что файлы лежат в корневой папке
  publish = "."
  # Команда сборки не нужна для чистого HTML/CSS, но поле оставим пустым или закомментируем
  # command = ""

# Базовые настройки для продакшена
[context.production.environment]
  NODE_VERSION = "20" # Если вдруг в будущем захотите добавить сборку

# Настройки перенаправлений (если понадобятся)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

